name: delete-tags

on:
  repository_dispatch:
  workflow_dispatch:
  watch:
     types: started

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Delete tags
      uses: fabriziocacicia/delete-tags-without-release-action@v0.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
