name: delete-tags

on:
  repository_dispatch:
  workflow_dispatch:
  watch:
     types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Delete tags
      uses: Huanyueyichen/delete-tags-without-release-action@v0.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          retain_days: 1
          keep_minimum_runs: 1
